services:
  # Shared RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shared-rabbitmq
    hostname: shared-rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - shared_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - iot-shared-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # TimescaleDB Database
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: datalogger-timescaledb
    environment:
      POSTGRES_DB: hotel_iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TIMESCALEDB_TELEMETRY: 'off'
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./datalogger-agent/init_db.sql:/docker-entrypoint-initdb.d/01-init_db.sql:ro
      - ./datalogger-agent/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro
      - ./datalogger-agent/docker-init-db.sh:/docker-entrypoint-initdb.d/03-init-script.sh:ro
    networks:
      - iot-shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hotel_iot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # IAQ Sensor Agent
  iaq-agent:
    image: chakorntestiot.azurecr.io/iot_iaq-agent:v1
    container_name: iaq-sensor-agent
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      # CSV Data Configuration (Multi-file mode)
      CSV_DIRECTORY_PATH: /app/data
      CSV_FILE_PATTERN: "*.csv"
      CSV_READING_MODE: chronological
      
      # Scheduler Configuration
      SEND_INTERVAL: ${SEND_INTERVAL:-5}
      BATCH_SIZE: ${BATCH_SIZE:-1}
      MAX_RETRIES: ${MAX_RETRIES:-3}
      RETRY_DELAY: ${RETRY_DELAY:-2}
      ENABLE_REPLAY: ${ENABLE_REPLAY:-true}
      
      # Logging Configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      STATS_INTERVAL: ${STATS_INTERVAL:-60}
      
      # RabbitMQ Configuration
      RABBITMQ_HOST: shared-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE:-iaq_data_queue}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE:-}
      RABBITMQ_ROUTING_KEY: ${RABBITMQ_ROUTING_KEY:-}
      RABBITMQ_DURABLE: ${RABBITMQ_DURABLE:-true}
      RABBITMQ_CONNECTION_TIMEOUT: ${RABBITMQ_CONNECTION_TIMEOUT:-30}
      RABBITMQ_HEARTBEAT: ${RABBITMQ_HEARTBEAT:-600}
      RABBITMQ_RETRY_DELAY: ${RABBITMQ_RETRY_DELAY:-5}
      RABBITMQ_MAX_RETRIES: ${RABBITMQ_MAX_RETRIES:-3}
    volumes:
      - ./sample_data:/app/data:ro
      - iaq_logs:/app/logs
    networks:
      - iot-shared-network
    healthcheck:
      test: ["CMD", "python", "-c", "print('IAQ Agent healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # DataLogger Agent
  datalogger-agent:
    image: chakorntestiot.azurecr.io/iot_datalogger-agent:v1
    container_name: datalogger-agent
    environment:
      # Database Configuration
      DATABASE_URL: postgresql://postgres:password@timescaledb:5432/hotel_iot
      
      # RabbitMQ Configuration
      RABBITMQ_HOST: shared-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_QUEUE: iaq_data_queue
      RABBITMQ_EXCHANGE: 
      RABBITMQ_ROUTING_KEY: 
      
      # Application Configuration
      BATCH_SIZE: 100
      BATCH_TIMEOUT: 30.0
      VALIDATOR_STRICT_MODE: "true"
      LOG_LEVEL: INFO
      
      # Python Configuration
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./datalogger-agent/logs:/app/logs
      - ./datalogger-agent/data:/app/data
    networks:
      - iot-shared-network
    depends_on:
      timescaledb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "print('DataLogger Agent healthy')"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  iot-shared-network:
    driver: bridge
    name: iot-shared-network

volumes:
  shared_rabbitmq_data:
    name: shared-rabbitmq-data
  timescaledb_data:
    external: true  
    name: datalogger-timescaledb-data
  iaq_logs:
    external: true
    name: iaq-agent-logs